%define     test_script $(pwd)/packaging/run_unittests.sh

Name:       nnstreamer-edge
Summary:    Common library set for nnstreamer-edge
Version:    0.0.1
Release:    1
Group:      Machine Learning/ML Framework
Packager:   Sangjung Woo <sangjung.woo@samsung.com>
License:    Apache-2.0
Source0:    %{name}-%{version}.tar.gz
Source1001: nnstreamer-edge.manifest

BuildRequires:  cmake
BuildRequires:  pkgconfig(paho-mqtt-c)
%if 0%{?check_test}
BuildRequires:  gtest-devel
%endif

%if 0%{?testcoverage}
BuildRequires:	lcov
%endif

%description
nnstreamer-edge provides remote source nodes for NNStreamer pipelines without GStreamer dependencies.
It also contains communicaton library for sharing server node information & status

%package -n ml-edge-mqtt
Summary: communication library for edge devices
%description -n ml-edge-mqtt
It is a communication library for edge devices.
This library supports publishing the MQTT messages to the GStreamer pipeline without GStreamer / Glib dependency
and subscribing the MQTT topic message from the broker.

%package -n ml-edge-mqtt-test
Summary: test program for ml-edge-mqtt library
%description -n ml-edge-mqtt-test
It is a test program for ml-edge-mqtt library.
It read the jpeg data and publishes it as "TestTopic" topic name 10 times.
If data is successfully received, then the image is shown on the server-side.

%package -n ml-edge-mqtt-devel
Summary: development package for ml-edge-mqtt-devel
Requires: nnstreamer-edge = %{version}-%{release}
%description -n ml-edge-mqtt-devel
It is a development package for ml-edge-mqtt-devel.

%if 0%{?testcoverage}
%package unittest-coverage
Summary: Unittest coverage result for nnstreamer-edge
%description unittest-coverage
HTML pages of lcov results of nnstreamer-edge generated during rpm build
%endif

%define enable_test -DENABLE_TEST=OFF
%if 0%{?check_test}
%define enable_test -DENABLE_TEST=ON
%endif

%prep
%setup -q
cp %{SOURCE1001} .

%build

%if 0%{?testcoverage}
# To test coverage, disable optimizations (and should unset _FORTIFY_SOURCE to use -O0)
CFLAGS=`echo $CFLAGS | sed -e "s|-O[1-9]|-O0|g"`
CFLAGS=`echo $CFLAGS | sed -e "s|-Wp,-D_FORTIFY_SOURCE=[1-9]||g"`
CXXFLAGS=`echo $CXXFLAGS | sed -e "s|-O[1-9]|-O0|g"`
CXXFLAGS=`echo $CXXFLAGS | sed -e "s|-Wp,-D_FORTIFY_SOURCE=[1-9]||g"`

export CFLAGS+=" -fprofile-arcs -ftest-coverage -g"
export CXXFLAGS+=" -fprofile-arcs -ftest-coverage -g"
export FFLAGS+=" -fprofile-arcs -ftest-coverage -g"
export LDFLAGS+=" -lgcov"
%endif

mkdir -p build
pushd build
%cmake .. \
    -DCMAKE_INSTALL_PREFIX=%{_prefix} \
    -DVERSION=%{version} %{enable_test}

make %{?jobs:-j%jobs}
popd

%install
rm -rf %{buildroot}
pushd build
%make_install
popd

%if 0%{?check_test}
LD_LIBRARY_PATH=./src bash %{test_script} ./tests/unittest_edge_mqtt
%endif

%if 0%{?testcoverage}
# 'lcov' generates the date format with UTC time zone by default. Let's replace UTC with KST.
# If you can get a root privilege, run ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
TZ='Asia/Seoul'; export TZ

# Get commit info
VCS=`cat ${RPM_SOURCE_DIR}/nnstreamer-edge.spec | grep "^VCS:" | sed "s|VCS:\\W*\\(.*\\)|\\1|"`

# Create human readable coverage report web page.
# Create null gcda files if gcov didn't create it because there is completely no unit test for them.
find . -name "*.gcno" -exec sh -c 'touch -a "${1%.gcno}.gcda"' _ {} \;
# Remove gcda for meaningless file (CMake's autogenerated)
find . -name "CMakeCCompilerId*.gcda" -delete
find . -name "CMakeCXXCompilerId*.gcda" -delete
# Generate report
lcov -t 'NNStreamer-edge unittest coverage' -o unittest.info -c -d . -b $(pwd) --no-external
# Exclude test files.
lcov -r unittest.info "*/tests/*" -o unittest-filtered.info
# Visualize the report
genhtml -o result unittest-filtered.info -t "NNStreamer-edge %{version}-%{release} ${VCS}" --ignore-errors source -p ${RPM_BUILD_DIR}

mkdir -p %{buildroot}%{_datadir}/nnstreamer-edge/unittest/
cp -r result %{buildroot}%{_datadir}/nnstreamer-edge/unittest/
%endif # test coverage

%clean
rm -rf %{buildroot}

%files -n ml-edge-mqtt
%manifest nnstreamer-edge.manifest
%defattr(-,root,root,-)
%{_libdir}/libcapi-edge-mqtt.so*

%if 0%{?check_test}
%files -n ml-edge-mqtt-test
%manifest nnstreamer-edge.manifest
%defattr(-,root,root,-)
%{_bindir}/test_edge_mqtt
%endif

%files -n ml-edge-mqtt-devel
%{_includedir}/ml-edge-mqtt.h
%{_libdir}/pkgconfig/ml-edge-mqtt.pc

%if 0%{?testcoverage}
%files unittest-coverage
%{_datadir}/nnstreamer-edge/unittest/*
%endif
