name: Integration test on GBS Tizen/x64 from Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        include:
          - aarch: "-A x86_64"
          - aarch: "-A armv7l"
          - aarch: "-A aarch64"

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: prepare deb sources for GBS
      run: echo "deb [trusted=yes] http://download.tizen.org/tools/latest-release/Ubuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/tizen.list
    - name: install GBS
      run: sudo apt-get update && sudo apt-get install -y gbs
    - name: configure GBS
      run: cp .github/workflows/tizen.gbs.conf ~/.gbs.conf
    - name: run GBS
      run: gbs build ${{ matrix.aarch }}
    - name: get nnstreamer-main
      run: git clone https://github.com/nnstreamer/nnstreamer.git
    - name: run GBS on nnstreamer with unit test
      run: |
        pushd nnstreamer
        gbs build ${{ matrix.aarch }} --define "edge_test 1"
        popd
## @todo run nnstreamer-edge related test cases only
